### ISSUE TITLE
Drawing 'inTube'

### ISSUE THREAD

**Issue by ravishwetha** [ravishwetha/SQ#1]
The red balls should originate from a tube on the right side of the screen (currently a white rectangle found on the top left of the screen).

**Comment by ravishwetha** [comment]
The white rectangle is in the proper position now but the tube shouldn't just be a white rectangle.

**Comment by SoniaBala** [comment]
I was trying something to make the tube look kinda cylindrical. I inserted this snippet of code in the drawInTube function along with the code for the rectangle, but there was a small issue:

sf::CircleShape leftEnd;
leftEnd.setFillColor(sf::Color::White);
leftEnd.setOutlineColor(sf::Color::Black); /\* The black outline is not showing up though. Do you know why? _/
leftEnd.setRadius(height/2);
leftEnd.setPosition(RES_X - width_2/3, RES_Y2);
leftEnd.setOrigin(width / 2.0, height / 2.0);
window->draw(leftEnd);

**Comment by ravishwetha** [comment]
Hey I added your code and it works great, the only thing missing was leftEnd.setOutline thickness because the default thickness with just outline color is 0 pixels.

sf::CircleShape leftEnd;
    leftEnd.setFillColor(inner);
    leftEnd.setOutlineColor(sf::Color::Black);
    leftEnd.setOutlineThickness((height/5.0)); //Thickness can be negative so that the outline expands from the border towards center instead of increasing the shape's size.
    leftEnd.setRadius(height/2);
    leftEnd.setOrigin(width/2.0, height/2.0);
    leftEnd.setPosition(RES_X - width*(2.0/3.0), RES_Y2);
    window->draw(leftEnd);

**Comment by SoniaBala** [comment]
oh thanks! So are you looking for changes like this geometrically to make it look better or do you want to import images to make it resemble a tube better? Um, and this is not just concerning the InTube, but the whole game itself?

**Comment by ravishwetha** [comment]
Hmm I was concerned about using stock images because I was afraid the art style of the game wouldn't come together properly. I definitely think imported images would look better on the components individually but I'm not sure how it would look together. It would take a lot of experimenting which I decided to put off. I thought our simplest working version should have generated shapes put together decently and then we could brush it up.
