### ISSUE TITLE
Adding a simple main menu

### ISSUE THREAD

**Issue by ravishwetha** [ravishwetha/SQ#6]
It could just display game title and say ''press enter to start."

**Comment by SoniaBala** [comment]
I did some searching and wrote a little code for the Splash Screen and a main Menu (SplashScreen.cpp/h and MainMenu.cpp/h) but I am not sure how to call those in the main.cpp file. 
I tried to include the following:

void initialiseGame() {
    SplashScreen splashScreen;
    splashScreen.Show(*window);
    //cout << "about to initialise lvl 1.\n";
    initialiseLevel1();
}

but there was no change in the output. Then I realised maybe it just runs over the code so fast that it is not visible to see the splash screen appearing. So I tried to put the initializeLevel1() as a comment like this:

void initialiseGame() {
    SplashScreen splashScreen;
    splashScreen.Show(*window);
    //cout << "about to initialise lvl 1.\n";
    //initialiseLevel1();
}

Still there was no change. Any idea why? I am still trying to figure out how to incorporate the MainMenu.cpp into the main.cpp code as well.

**Comment by ravishwetha** [comment]
Could I see the code for Splashscreen.cpp/h and MainMenu.cpp/h? If the function splashScreen.show() is something like this in the cpp file:

void splashScreen::show() {
   window->clear()
  _draw splashscreen code_
   window->display() 
}

you won't have to worry about the code running through it too quickly. 

If you want to include the contents of a header and cpp file on main.cpp you have to write #include "Splashscreen.h" in both main.cpp and Splashscreen.cpp. You're linking them through the header file. The syntax for writing h and cpp files is different from directly declaring a class or function in main.cpp. You can use the other files in this repository as an example for syntax. This was my first time splitting a program into different files too, it greatly reduced compilation time.

**Comment by SoniaBala** [comment]
sorry there was a problem and the files didn't upload into the folder the other day. They are in there now. And thanks for the explanation

**Comment by ravishwetha** [comment]
Hey, could you also add MainMenu.png and Stacks and Queues.png, also where do you use the MainMenu class in main.cpp?

**Comment by ravishwetha** [comment]
Hi, I could get the main menu working with the present code, I'm wondering what you had in mind for the splash screen. Do you want it to display the first time the game loads or every time before the main menu is called?

**Comment by SoniaBala** [comment]
Um the first time the game loads
